// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYOcmUivmUgzaaEeEUY90Woq6HB8iykzI',
    appId: '1:565238316024:web:81654bee2de955fdc4740d',
    messagingSenderId: '565238316024',
    projectId: 'whatsapp-messenger-27607',
    authDomain: 'whatsapp-messenger-27607.firebaseapp.com',
    storageBucket: 'whatsapp-messenger-27607.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8qNUoW6UZ6EawqBgQRZBTqA9nV-vBzWc',
    appId: '1:565238316024:android:a52312736c145097c4740d',
    messagingSenderId: '565238316024',
    projectId: 'whatsapp-messenger-27607',
    storageBucket: 'whatsapp-messenger-27607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmq_mxnICOs-Z0cf_f8R9L6SFFMMyYLHc',
    appId: '1:565238316024:ios:f3b432eb002dab53c4740d',
    messagingSenderId: '565238316024',
    projectId: 'whatsapp-messenger-27607',
    storageBucket: 'whatsapp-messenger-27607.appspot.com',
    iosClientId: '565238316024-llvik0e0vl0rvq8p80lrm4u7rfrq6osj.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmq_mxnICOs-Z0cf_f8R9L6SFFMMyYLHc',
    appId: '1:565238316024:ios:f3b432eb002dab53c4740d',
    messagingSenderId: '565238316024',
    projectId: 'whatsapp-messenger-27607',
    storageBucket: 'whatsapp-messenger-27607.appspot.com',
    iosClientId: '565238316024-llvik0e0vl0rvq8p80lrm4u7rfrq6osj.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );
}
